# Generated by Django 5.0.3 on 2024-03-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_appointment_accepted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='req_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
